// src/lib/astro-engine/nakshatra-data.ts
// AstroLife — Authentic 27-Nakshatra Classical Master Dictionary
// Contains Complete Metadata: Devta, Animal, Bird, Tree, Symbol, Tattva, Paryaya, Rashi Spans

export type ElementTattva = "Agni" | "Prithvi" | "Vayu" | "Jala";
export type ParyayaType = "Prathama" | "Dvitiya" | "Tritiya";
export type ParyayaIntensity = "Base" | "Moderate" | "Peak";

export interface NakshatraData {
  id: number; // 1 to 27
  name: string;
  lord: "Ketu" | "Venus" | "Sun" | "Moon" | "Mars" | "Rahu" | "Jupiter" | "Saturn" | "Mercury";
  devta: string;
  devtaDescription: string;
  animal: string;
  bird: string;
  tree: string;
  symbol: string;
  tattva: ElementTattva;
  paryaya: ParyayaType;
  paryayaIntensity: ParyayaIntensity;
  startDeg: number;
  endDeg: number;
  rashiSpan: string;
  primaryQuality: string;
}

export const NAKSHATRA_DATA: NakshatraData[] = [
  {
    id: 1,
    name: "Ashwini",
    lord: "Ketu",
    devta: "Ashwini Kumaras",
    devtaDescription: "Twin golden horsemen of dawn, physicians of the Devas, bearers of healing and speed",
    animal: "Horse (Ashva)",
    bird: "Hawk (Shikra)",
    tree: "Indian Laburnum (Kuchila / Strychnos nux-vomica)",
    symbol: "Horse Head (Speed & Healing Vitality)",
    tattva: "Agni",
    paryaya: "Prathama",
    paryayaIntensity: "Base",
    startDeg: 0,
    endDeg: 13.333333333333334,
    rashiSpan: "Aries 00°00' - 13°20'",
    primaryQuality: "Instantaneous initiative, therapeutic vitality, swift movement",
  },
  {
    id: 2,
    name: "Bharani",
    lord: "Venus",
    devta: "Yama",
    devtaDescription: "Lord of Dharma, cosmic justice, and evolutionary transformation across thresholds",
    animal: "Elephant (Gaja)",
    bird: "Crow (Kaka)",
    tree: "Amla / Indian Gooseberry (Phyllanthus emblica)",
    symbol: "Yoni / Vomb (Creation, Containment & Rebirth)",
    tattva: "Prithvi",
    paryaya: "Prathama",
    paryayaIntensity: "Base",
    startDeg: 13.333333333333334,
    endDeg: 26.666666666666668,
    rashiSpan: "Aries 13°20' - 26°40'",
    primaryQuality: "Endurance, gestational depth, moral discipline under fire",
  },
  {
    id: 3,
    name: "Krittika",
    lord: "Sun",
    devta: "Agni",
    devtaDescription: "Sacred fire deity, divine priest of transformation, burner of impurities",
    animal: "Sheep / Ram (Mesha)",
    bird: "Peacock (Mayura)",
    tree: "Gular / Cluster Fig (Ficus racemosa)",
    symbol: "Razor / Flame / Axe (Cutting Through Illusion)",
    tattva: "Agni",
    paryaya: "Prathama",
    paryayaIntensity: "Base",
    startDeg: 26.666666666666668,
    endDeg: 40.0,
    rashiSpan: "Aries 26°40' - Taurus 10°00'",
    primaryQuality: "Purifying sharpness, decisive discernment, noble courage",
  },
  {
    id: 4,
    name: "Rohini",
    lord: "Moon",
    devta: "Prajapati / Brahma",
    devtaDescription: "Lord of creation, fertility, artistic flourishing and manifest beauty",
    animal: "Serpent / Cobra (Sarpa)",
    bird: "Owl (Uluka)",
    tree: "Jamun / Black Plum (Syzygium cumini)",
    symbol: "Chariot / Cart / Temple (Luxurious Progression & Commerce)",
    tattva: "Prithvi",
    paryaya: "Prathama",
    paryayaIntensity: "Base",
    startDeg: 40.0,
    endDeg: 53.333333333333336,
    rashiSpan: "Taurus 10°00' - 23°20'",
    primaryQuality: "Sensory elegance, material manifestation, magnetic charm",
  },
  {
    id: 5,
    name: "Mrigashira",
    lord: "Mars",
    devta: "Soma / Chandra",
    devtaDescription: "Lord of nectar, celestial intuition, questing mind and rejuvenation",
    animal: "Serpent (Sarpa)",
    bird: "Hen / Partidge (Kukkuta)",
    tree: "Khadira / Cutch Tree (Senegalia catechu)",
    symbol: "Deer's Head (Curiosity, Research & The Eternal Search)",
    tattva: "Prithvi",
    paryaya: "Prathama",
    paryayaIntensity: "Base",
    startDeg: 53.333333333333336,
    endDeg: 66.66666666666667,
    rashiSpan: "Taurus 23°20' - Gemini 06°40'",
    primaryQuality: "Inquisitive intellect, agile tracking of truth, adaptability",
  },
  {
    id: 6,
    name: "Ardra",
    lord: "Rahu",
    devta: "Rudra",
    devtaDescription: "Lord of cosmic storms, piercing wisdom, and breakthrough catharsis",
    animal: "Dog (Shvana)",
    bird: "Andean Condor / Heron",
    tree: "Krishna Agaru / Agarwood (Aquilaria agallocha)",
    symbol: "Teardrop / Diamond (Purification Through Storm)",
    tattva: "Jala",
    paryaya: "Prathama",
    paryayaIntensity: "Base",
    startDeg: 66.66666666666667,
    endDeg: 80.0,
    rashiSpan: "Gemini 06°40' - 20°00'",
    primaryQuality: "Intellectual breakthrough, cathartic honesty, psychological depth",
  },
  {
    id: 7,
    name: "Punarvasu",
    lord: "Jupiter",
    devta: "Aditi",
    devtaDescription: "Cosmic Mother of the Aditya gods, boundless sky of grace and restoration",
    animal: "Cat (Marjara)",
    bird: "Swan (Hamsa)",
    tree: "Bamboo (Vamsha / Bambusa bambos)",
    symbol: "Quiver of Arrows (Return of Light & Second Chances)",
    tattva: "Jala",
    paryaya: "Prathama",
    paryayaIntensity: "Base",
    startDeg: 80.0,
    endDeg: 93.33333333333333,
    rashiSpan: "Gemini 20°00' - Cancer 03°20'",
    primaryQuality: "Benevolent resilience, spiritual renewal, returning home",
  },
  {
    id: 8,
    name: "Pushya",
    lord: "Saturn",
    devta: "Brihaspati",
    devtaDescription: "Guru of the Devas, master of sacred prayer, ritual and wisdom",
    animal: "Goat / Ram (Basta)",
    bird: "Sea Crow / Woodpecker",
    tree: "Peepal / Sacred Fig (Ficus religiosa)",
    symbol: "Cow's Udder / Lotus / Circle (Nourishment & Dharma)",
    tattva: "Jala",
    paryaya: "Prathama",
    paryayaIntensity: "Base",
    startDeg: 93.33333333333333,
    endDeg: 106.66666666666667,
    rashiSpan: "Cancer 03°20' - 16°40'",
    primaryQuality: "Steadfast nourishment, dharmic counseling, ethical strength",
  },
  {
    id: 9,
    name: "Ashlesha",
    lord: "Mercury",
    devta: "Sarpas / Nagas",
    devtaDescription: "Serpent deities of primal subterranean power, esoteric wisdom and kundalini",
    animal: "Male Cat (Marjara)",
    bird: "Small Blue Sparrow (Chil)",
    tree: "Nagchampa / Ironwood (Mesua ferrea)",
    symbol: "Coiled Serpent (Occult Perception & Clinging Embrace)",
    tattva: "Jala",
    paryaya: "Prathama",
    paryayaIntensity: "Base",
    startDeg: 106.66666666666667,
    endDeg: 120.0,
    rashiSpan: "Cancer 16°40' - 30°00'",
    primaryQuality: "Penetrating psychology, occult perception, protective instinct",
  },
  {
    id: 10,
    name: "Magha",
    lord: "Ketu",
    devta: "Pitris",
    devtaDescription: "Ancestral fathers, guardian spirits of the bloodline and lineage sovereignty",
    animal: "Male Rat (Mushaka)",
    bird: "Male Eagle (Garuda)",
    tree: "Banyan / Bargad (Ficus benghalensis)",
    symbol: "Royal Throne Room / Palanquin (Sovereign Authority)",
    tattva: "Agni",
    paryaya: "Dvitiya",
    paryayaIntensity: "Moderate",
    startDeg: 120.0,
    endDeg: 133.33333333333334,
    rashiSpan: "Leo 00°00' - 13°20'",
    primaryQuality: "Lineage pride, ancestral honor, executive dignity",
  },
  {
    id: 11,
    name: "Purva Phalguni",
    lord: "Venus",
    devta: "Bhaga",
    devtaDescription: "God of legitimate prosperity, marital affection, joy and shared fortune",
    animal: "Female Rat (Mushika)",
    bird: "Chakor / Francolin Partridge",
    tree: "Palash / Flame of the Forest (Butea monosperma)",
    symbol: "Front Legs of Couch / Hammock (Restful Creation & Art)",
    tattva: "Jala",
    paryaya: "Dvitiya",
    paryayaIntensity: "Moderate",
    startDeg: 133.33333333333334,
    endDeg: 146.66666666666666,
    rashiSpan: "Leo 13°20' - 26°40'",
    primaryQuality: "Creative charisma, social warmth, relaxed abundance",
  },
  {
    id: 12,
    name: "Uttara Phalguni",
    lord: "Sun",
    devta: "Aryaman",
    devtaDescription: "God of contracts, nobility, sacred patron-client covenants and friendship",
    animal: "Cow / Bull (Go)",
    bird: "Beetle / Golden Oriole",
    tree: "Rudraksha / Indian Laurel (Ficus microcarpa)",
    symbol: "Back Legs of Couch (Steadfast Covenant & Philanthropy)",
    tattva: "Agni",
    paryaya: "Dvitiya",
    paryayaIntensity: "Moderate",
    startDeg: 146.66666666666666,
    endDeg: 160.0,
    rashiSpan: "Leo 26°40' - Virgo 10°00'",
    primaryQuality: "Dharmic patronage, loyal alliances, civic leadership",
  },
  {
    id: 13,
    name: "Hasta",
    lord: "Moon",
    devta: "Savitur",
    devtaDescription: "Solar deity of dawn inspiration, craftsmanship and the golden transforming touch",
    animal: "Female Buffalo (Mahishi)",
    bird: "Vulture / Indian Kite",
    tree: "Jaee / Hog Plum (Spondias pinnata)",
    symbol: "Open Hand / Clenched Fist (Skillful Execution & Manifestation)",
    tattva: "Prithvi",
    paryaya: "Dvitiya",
    paryayaIntensity: "Moderate",
    startDeg: 160.0,
    endDeg: 173.33333333333334,
    rashiSpan: "Virgo 10°00' - 23°20'",
    primaryQuality: "Precision craftsmanship, analytical resourcefulness, practical dexterity",
  },
  {
    id: 14,
    name: "Chitra",
    lord: "Mars",
    devta: "Tvashtar / Vishwakarma",
    devtaDescription: "Divine architect, master sculptor, creator of exquisite cosmic forms",
    animal: "Female Tiger (Vyaghri)",
    bird: "Woodpecker",
    tree: "Bilva / Bael Tree (Aegle marmelos)",
    symbol: "Bright Jewel / Pearl (Exquisite Design & Structural Genius)",
    tattva: "Vayu",
    paryaya: "Dvitiya",
    paryayaIntensity: "Moderate",
    startDeg: 173.33333333333334,
    endDeg: 186.66666666666666,
    rashiSpan: "Virgo 23°20' - Libra 06°40'",
    primaryQuality: "Architectural mastery, aesthetic perfectionism, structural innovation",
  },
  {
    id: 15,
    name: "Swati",
    lord: "Rahu",
    devta: "Vayu",
    devtaDescription: "Lord of winds, breath of life, freedom of movement and commercial currents",
    animal: "Male Buffalo (Mahisha)",
    bird: "Pigeon / Sparrow (Kapot)",
    tree: "Arjuna Tree (Terminalia arjuna)",
    symbol: "Young Shoot Blown by Wind / Coral (Graceful Independence)",
    tattva: "Vayu",
    paryaya: "Dvitiya",
    paryayaIntensity: "Moderate",
    startDeg: 186.66666666666666,
    endDeg: 200.0,
    rashiSpan: "Libra 06°40' - 20°00'",
    primaryQuality: "Diplomatic adaptability, commercial agility, love of autonomy",
  },
  {
    id: 16,
    name: "Vishakha",
    lord: "Jupiter",
    devta: "Indra & Agni",
    devtaDescription: "Dual deities of sovereign command and focused sacrificial energy",
    animal: "Male Tiger (Vyaghra)",
    bird: "Red Crested Falcon",
    tree: "Vikankata / Kaith (Flacourtia indica)",
    symbol: "Triumphal Arch / Potter's Wheel (Single-Pointed Victory)",
    tattva: "Agni",
    paryaya: "Dvitiya",
    paryayaIntensity: "Moderate",
    startDeg: 200.0,
    endDeg: 213.33333333333334,
    rashiSpan: "Libra 20°00' - Scorpio 03°20'",
    primaryQuality: "Unrelenting ambition, competitive focus, triumph through endurance",
  },
  {
    id: 17,
    name: "Anuradha",
    lord: "Saturn",
    devta: "Mitra",
    devtaDescription: "Solar deity of harmonious friendship, devotion, alliances and universal trust",
    animal: "Female Deer (Harini)",
    bird: "Nightingale / Peacock",
    tree: "Bakula / Medlar (Mimusops elengi)",
    symbol: "Lotus Flower / Staff (Devotion Rising Untouched from Mud)",
    tattva: "Jala",
    paryaya: "Dvitiya",
    paryayaIntensity: "Moderate",
    startDeg: 213.33333333333334,
    endDeg: 226.66666666666666,
    rashiSpan: "Scorpio 03°20' - 16°40'",
    primaryQuality: "Enduring friendship, devotional fortitude, organizational diplomacy",
  },
  {
    id: 18,
    name: "Jyeshtha",
    lord: "Mercury",
    devta: "Indra",
    devtaDescription: "King of the Devas, bearer of the thunderbolt, guardian of sacred borders",
    animal: "Male Deer (Mriga)",
    bird: "Brahminy Kite",
    tree: "Shaalmali / Silk Cotton Tree (Bombax ceiba)",
    symbol: "Circular Amulet / Talisman / Earring (Protective Primacy)",
    tattva: "Vayu",
    paryaya: "Dvitiya",
    paryayaIntensity: "Moderate",
    startDeg: 226.66666666666666,
    endDeg: 240.0,
    rashiSpan: "Scorpio 16°40' - 30°00'",
    primaryQuality: "Senior authority, strategic defense, intellectual sovereignty",
  },
  {
    id: 19,
    name: "Mula",
    lord: "Ketu",
    devta: "Nirriti",
    devtaDescription: "Goddess of dissolution, foundational root truth, stripping away illusions",
    animal: "Male Dog (Shvana)",
    bird: "Red Vulture",
    tree: "Salai / White Dammar (Boswellia serrata)",
    symbol: "Tied Bundle of Roots / Elephant Goad (Root Investigation)",
    tattva: "Agni",
    paryaya: "Tritiya",
    paryayaIntensity: "Peak",
    startDeg: 240.0,
    endDeg: 253.33333333333334,
    rashiSpan: "Sagittarius 00°00' - 13°20'",
    primaryQuality: "Radical research, fundamental resetting, fearlessness at the root",
  },
  {
    id: 20,
    name: "Purva Ashadha",
    lord: "Venus",
    devta: "Apah",
    devtaDescription: "Cosmic waters of invocation, flowing invincibility and deep emotional purification",
    animal: "Male Monkey (Vanara)",
    bird: "Francolin / Wild Duck",
    tree: "Jamu / Sita Ashok (Saraca asoca)",
    symbol: "Winnowing Fan / Elephant Tusk (Unconquerable Invincibility)",
    tattva: "Jala",
    paryaya: "Tritiya",
    paryayaIntensity: "Peak",
    startDeg: 253.33333333333334,
    endDeg: 266.6666666666667,
    rashiSpan: "Sagittarius 13°20' - 26°40'",
    primaryQuality: "Invincible confidence, magnetic oratory, grand prosperity",
  },
  {
    id: 21,
    name: "Uttara Ashadha",
    lord: "Sun",
    devta: "Vishvadevas",
    devtaDescription: "The ten universal deities personifying Truth, Will, Time and Righteous Duty",
    animal: "Male Mongoose (Nakula)",
    bird: "Stork / Blue Jay",
    tree: "Jackfruit / Phanas (Artocarpus heterophyllus)",
    symbol: "Small Planks of Bed / Elephant Tusk (Final Enduring Victory)",
    tattva: "Agni",
    paryaya: "Tritiya",
    paryayaIntensity: "Peak",
    startDeg: 266.6666666666667,
    endDeg: 280.0,
    rashiSpan: "Sagittarius 26°40' - Capricorn 10°00'",
    primaryQuality: "Institutional statesmanship, unshakable integrity, enduring victory",
  },
  {
    id: 22,
    name: "Shravana",
    lord: "Moon",
    devta: "Vishnu",
    devtaDescription: "The Supreme Preserver, pervader of cosmic order through sacred hearing and speech",
    animal: "Female Monkey (Vanari)",
    bird: "Spotted Eagle / Heron",
    tree: "Arka / Crown Flower (Calotropis gigantea)",
    symbol: "Three Footprints / Ear (Sacred Listening & Universal Learning)",
    tattva: "Vayu",
    paryaya: "Tritiya",
    paryayaIntensity: "Peak",
    startDeg: 280.0,
    endDeg: 293.3333333333333,
    rashiSpan: "Capricorn 10°00' - 23°20'",
    primaryQuality: "Deep scholarship, attentive listening, preservation of timeless wisdom",
  },
  {
    id: 23,
    name: "Dhanishta",
    lord: "Mars",
    devta: "Ashta Vasus",
    devtaDescription: "Eight deities of material abundance, elemental light, rhythm and earthly stability",
    animal: "Female Lion (Simhi)",
    bird: "Golden Bee / Peacock",
    tree: "Shami / Khejri Tree (Prosopis cineraria)",
    symbol: "Mridangam Drum / Flute (Rhythmic Mastery & Wealth)",
    tattva: "Prithvi",
    paryaya: "Tritiya",
    paryayaIntensity: "Peak",
    startDeg: 293.3333333333333,
    endDeg: 306.6666666666667,
    rashiSpan: "Capricorn 23°20' - Aquarius 06°40'",
    primaryQuality: "Rhythmic synchronization, material leadership, generous manifestation",
  },
  {
    id: 24,
    name: "Shatabhisha",
    lord: "Rahu",
    devta: "Varuna",
    devtaDescription: "Lord of cosmic waters, keeper of celestial law, master of a hundred healing physicians",
    animal: "Female Horse (Ashva)",
    bird: "Raven / Great Horned Owl",
    tree: "Kadamba Tree (Neolamarckia cadamba)",
    symbol: "Empty Circle / 100 Physicians (Occult Healing & Boundary Seclusion)",
    tattva: "Vayu",
    paryaya: "Tritiya",
    paryayaIntensity: "Peak",
    startDeg: 306.6666666666667,
    endDeg: 320.0,
    rashiSpan: "Aquarius 06°40' - 20°00'",
    primaryQuality: "Esoteric diagnosis, independent seclusion, visionary healing",
  },
  {
    id: 25,
    name: "Purva Bhadrapada",
    lord: "Jupiter",
    devta: "Aja Ekapada",
    devtaDescription: "The one-footed cosmic serpent/fire goat, intense ascetic fire of higher consciousness",
    animal: "Male Lion (Simha)",
    bird: "Pigeon / Falcon",
    tree: "Mango Tree (Mangifera indica)",
    symbol: "Front of Funeral Cot / Two-Faced Man (Ascetic Awakening)",
    tattva: "Agni",
    paryaya: "Tritiya",
    paryayaIntensity: "Peak",
    startDeg: 320.0,
    endDeg: 333.33333333333334,
    rashiSpan: "Aquarius 20°00' - Pisces 03°20'",
    primaryQuality: "Transformational intensity, spiritual non-conformity, fierce idealism",
  },
  {
    id: 26,
    name: "Uttara Bhadrapada",
    lord: "Saturn",
    devta: "Ahirbudhnya",
    devtaDescription: "The serpent of the deep cosmic ocean, serene wisdom anchored in quiet depths",
    animal: "Female Cow (Go)",
    bird: "Kotwal / King Crow",
    tree: "Neem Tree (Azadirachta indica)",
    symbol: "Back of Funeral Cot / Coiled Deep Snake (Meditative Stillness)",
    tattva: "Prithvi",
    paryaya: "Tritiya",
    paryayaIntensity: "Peak",
    startDeg: 333.33333333333334,
    endDeg: 346.6666666666667,
    rashiSpan: "Pisces 03°20' - 16°40'",
    primaryQuality: "Meditative depth, compassionate restraint, deep philosophical calm",
  },
  {
    id: 27,
    name: "Revati",
    lord: "Mercury",
    devta: "Pushan",
    devtaDescription: "Nourisher of journeys, protector of animals, guide across the final threshold",
    animal: "Female Elephant (Gaja)",
    bird: "Woodpecker / Heron",
    tree: "Mahua / Butter Tree (Madhuca longifolia)",
    symbol: "Fish Pair / Drum (Safe Passage, Compassion & Abundance)",
    tattva: "Jala",
    paryaya: "Tritiya",
    paryayaIntensity: "Peak",
    startDeg: 346.6666666666667,
    endDeg: 360.0,
    rashiSpan: "Pisces 16°40' - 30°00'",
    primaryQuality: "Universal compassion, safe completion of journeys, tender guardianship",
  },
];

// Fast lookup maps
export const NAKSHATRA_BY_ID = new Map<number, NakshatraData>(
  NAKSHATRA_DATA.map((n) => [n.id, n])
);

export const NAKSHATRA_BY_NAME = new Map<string, NakshatraData>(
  NAKSHATRA_DATA.map((n) => [n.name.toLowerCase(), n])
);

export function getNakshatraById(id: number): NakshatraData {
  const normId = ((id - 1) % 27 + 27) % 27 + 1;
  return NAKSHATRA_BY_ID.get(normId) ?? NAKSHATRA_DATA[0];
}

export function getNakshatraByName(name: string): NakshatraData | undefined {
  return NAKSHATRA_BY_NAME.get(name.trim().toLowerCase());
}
