import { makeRule } from "./_factory";

export const CAREER_RULES = [
  makeRule({ id: "saturn_visible_career_direction", title: "Visible Saturn/Fate career direction", category: "career", path: "lines.saturn.visible", value: true, sourceIds: ["WRITER_LINES_III"], classical: "Bhagya rekha dikhe to karmakshetra mein disha aur zimmedari ka yog hota hai.", scientific: "A visible Saturn/Fate line supports career orientation and responsibility.", luxury: "Your career map has a directional spine: long-term effort matters more than quick validation.", confidenceBase: 70 }),
  makeRule({ id: "sun_visible_public_work", title: "Visible Sun line public work", category: "career", path: "lines.sun.visible", value: true, classical: "Surya rekha kala, prashansa aur sarvajanik pehchan ka sanket deti hai.", scientific: "A visible Sun line supports reputation, creative visibility and public-facing work.", luxury: "Recognition is part of your growth architecture; skill must be made visible.", confidenceBase: 69 }),
  makeRule({ id: "mercury_visible_business", title: "Visible Mercury line business", category: "career", path: "lines.mercury.visible", value: true, classical: "Budh rekha vani, vyapar, lekhan aur sampark ke kaushal ko darshati hai.", scientific: "Visible Mercury line supports communication, networking and commercial intelligence.", luxury: "Your business signal is active: speaking, selling, teaching, advising or product thinking can compound.", confidenceBase: 70 }),
  makeRule({ id: "jupiter_mercury_founder", title: "Founder leadership pattern", category: "career", path: "mounts.jupiter.prominence", value: "strong", supporting: [{ path: "mounts.mercury.prominence", equals: "strong" }, { path: "thumb.length", equals: "long" }], classical: "Guru, Budh aur lamba angutha milkar netritva, vyapar aur sankalp ka yog banate hain.", scientific: "Leadership mount plus Mercury plus strong thumb supports entrepreneurship potential.", luxury: "Founder potential is present when your ambition is paired with communication and disciplined execution.", confidenceBase: 76 }),
  makeRule({ id: "sun_mercury_media", title: "Media and communication visibility", category: "career", path: "mounts.sun.prominence", value: "strong", supporting: [{ path: "mounts.mercury.prominence", equals: "strong" }], classical: "Surya-Budh bal kala, vani, vyapar aur lok pehchan ka sanyog dete hain.", scientific: "Sun plus Mercury supports communication-led recognition: media, teaching, advisory, marketing or design.", luxury: "Your best visibility comes through intelligent expression: voice, brand, design, teaching or digital products.", confidenceBase: 74 }),
  makeRule({ id: "head_clear_strategy", title: "Strategic career thinking", category: "career", path: "lines.head.clarity", value: "clear", supporting: [{ path: "thumb.secondPhalange", equals: "long" }], classical: "Spasht mastishk rekha aur yukti phal ka bal rananeeti mein safalta dete hain.", scientific: "Clear head line plus reasoning phalange supports strategic planning.", luxury: "You are strongest when decisions are mapped, sequenced and measured.", confidenceBase: 72 }),
  makeRule({ id: "moon_strong_creative_career", title: "Moon creativity career", category: "career", path: "mounts.moon.prominence", value: "strong", supporting: [{ path: "lines.head.direction", equals: "moon" }], classical: "Chandra bal aur mastishk rekha ki chandra disha kalpana, yatra aur rachna ko badhate hain.", scientific: "Strong Moon with moon-directed head line favors creative, travel, psychological or story-led careers.", luxury: "Your career gains depth when imagination becomes a structured offer.", confidenceBase: 72 }),
  makeRule({ id: "fate_absent_self_authored", title: "No visible fate line self-authored path", category: "career", path: "lines.saturn.visible", value: false, classical: "Bhagya rekha na dikhe to vyakti ko apna marg swayam banana padta hai; ise durbhagya na manein.", scientific: "Absent fate line is not failure; it often means nonlinear or self-authored career direction.", luxury: "Your path may not follow a standard ladder. Design the ladder instead of waiting for one.", confidenceBase: 60 }),
];
