import { makeRule } from "./_factory";

export const FINGER_RULES = [
  makeRule({ id: "fingers_long_detail", title: "Long fingers detail intelligence", category: "fingers", path: "fingers.length", value: "long", classical: "Lambi ungliyan vivaran, chintan aur suksma avlokan ka sanket hain.", scientific: "Long fingers point to detail orientation, analysis and refined perception.", luxury: "Your fingers show a precision mind: nuance, research and quality control are natural strengths.", confidenceBase: 69 }),
  makeRule({ id: "fingers_short_action", title: "Short fingers action bias", category: "fingers", path: "fingers.length", value: "short", classical: "Chhoti ungliyan jaldi nirnay, kriyatmakta aur seedhe vyavahar ko dikhati hain.", scientific: "Shorter fingers often indicate action bias and preference for fast decisions.", luxury: "You are built for motion: concise choices and visible progress keep your energy alive.", confidenceBase: 65 }),
  makeRule({ id: "tips_conic_creative", title: "Conic fingertips creativity", category: "fingers", path: "fingers.tips", value: "conic", classical: "Shankhakar anguli agra kala, bhavna aur adhyatmik grahan shakti ka sanket hai.", scientific: "Conic tips suggest creative, aesthetic and associative thinking.", luxury: "Your fingertips read refined and imaginative: creative taste can become a professional asset.", confidenceBase: 67 }),
  makeRule({ id: "tips_square_method", title: "Square fingertips method", category: "fingers", path: "fingers.tips", value: "square", classical: "Chaturasra agra niyam, paddhati aur vastu-nishtha ka pramaan hai.", scientific: "Square tips support method, order and practical judgement.", luxury: "Your hand values clarity: systems, routines and tangible outcomes strengthen your path.", confidenceBase: 67 }),
  makeRule({ id: "tips_spatulate_inventive", title: "Spatulate fingertips invention", category: "fingers", path: "fingers.tips", value: "spatulate", classical: "Spatulate agra prayog, khoj aur nayi disha ki ichha badhata hai.", scientific: "Spatulate tips favor experimentation, movement and inventive problem solving.", luxury: "Your fingers carry innovation charge: build, test, iterate, and keep the work alive.", confidenceBase: 66 }),
  makeRule({ id: "setting_balanced_social", title: "Balanced finger setting", category: "fingers", path: "fingers.setting", value: "balanced", classical: "Santulit anguli sthiti samajik samvedan aur vyavaharik santulan ko dikhati hai.", scientific: "Balanced setting suggests social calibration and stable self-presentation.", luxury: "Your hand shows social symmetry: you can read rooms without losing your own agenda.", confidenceBase: 66 }),
  makeRule({ id: "setting_uneven_mixed_talents", title: "Uneven finger setting mixed talents", category: "fingers", path: "fingers.setting", value: "uneven", classical: "Asaman anguli sthiti vividh pravrittiyon aur jeevan mein alag-alag balon ka sanket hai.", scientific: "Uneven setting may show mixed motivations and non-linear talent development.", luxury: "Your talent profile is not flat; it rises in unusual places and needs custom positioning.", confidenceBase: 63 }),
  makeRule({ id: "long_conic_fingers_articulate", title: "Long conic fingers articulate imagination", category: "fingers", path: "fingers.length", value: "long", supporting: [{ path: "fingers.tips", equals: "conic" }, { path: "lines.head.direction", equals: "moon" }], classical: "Lambi conic ungliyan mastishk rekha ke chandra disha se milkar kalpana aur abhivyakti ko badhati hain.", scientific: "Long conic fingers plus a moon-directed head line support imaginative communication.", luxury: "Your imagination is not vague; it wants language, design, story or advisory expression.", confidenceBase: 73 }),
];
