import { makeRule } from "./_factory";

export const HAND_SHAPE_RULES = [
  makeRule({ id: "hand_rectangular_active_mind", title: "Rectangular palm with active mind", category: "hand_shape", path: "palm.shape", value: "rectangular", sourceIds: ["DAYANAND_MASTER", "SAMUDRIK_SHASTRA"], classical: "Ayatakar hasta vyakti ko chanchal buddhi, prayogshil soch aur jeevan mein gati deta hai.", scientific: "A rectangular palm suggests adaptive thinking, curiosity and a need for mentally stimulating work.", luxury: "Your palm architecture shows a movement-oriented intelligence: ideas, travel, communication and learning want space.", confidenceBase: 70 }),
  makeRule({ id: "hand_square_practical", title: "Square palm practicality", category: "hand_shape", path: "palm.shape", value: "square", classical: "Chaturasra hasta sthirta, vyavaharik buddhi aur dhairya ka sanket hai.", scientific: "A square palm supports practical judgement, structure and reliable execution.", luxury: "Your hand carries the signature of grounded strategy: stable decisions, consistent work and practical authority.", confidenceBase: 70 }),
  makeRule({ id: "hand_conic_aesthetic", title: "Conic palm sensitivity", category: "hand_shape", path: "palm.shape", value: "conic", classical: "Komal/conic hasta kala, bhavna aur saundarya bodh ko badhata hai.", scientific: "A conic palm points to aesthetic sensitivity, emotional perception and creative response patterns.", luxury: "Your hand leans toward refined perception: taste, beauty, emotional tone and intuitive selection matter deeply.", confidenceBase: 66 }),
  makeRule({ id: "hand_spatulate_independent", title: "Spatulate palm independence", category: "hand_shape", path: "palm.shape", value: "spatulate", classical: "Vistrit ya spatulate hasta prayatna, prayog aur swatantra karya ka sanket deta hai.", scientific: "A spatulate palm favors initiative, experimentation and physical or entrepreneurial restlessness.", luxury: "You carry an innovator's hand: independent motion, practical invention and a dislike of stale routines.", confidenceBase: 67 }),
  makeRule({ id: "texture_supple_adaptive", title: "Supple palm adaptability", category: "hand_shape", path: "palm.texture", value: "supple", classical: "Komal-santulit sparsh samvedansheelta aur anukoolan shakti dikhata hai.", scientific: "Supple texture supports adaptability, emotional responsiveness and social calibration.", luxury: "Your energy system reads responsive rather than rigid: you adjust, sense and recover through intelligent flexibility.", confidenceBase: 65 }),
  makeRule({ id: "texture_firm_endurance", title: "Firm palm endurance", category: "hand_shape", path: "palm.texture", value: "firm", classical: "Dridh hasta mehnat, sahanshakti aur sthir sankalp ka pramaan hai.", scientific: "Firm texture points to stamina, practical drive and persistence under pressure.", luxury: "Your palm shows durable operating power: once committed, your system can sustain long arcs of work.", confidenceBase: 66 }),
  makeRule({ id: "line_density_many_processing", title: "Many lines processing load", category: "hand_shape", path: "palm.lineDensity", value: "many", sourceIds: ["FIFTY_HANDPRINTS", "WRITER_LINES_III"], classical: "Bahut rekhaen adhik soch, samvedansheelta aur paristithiyon se prabhavit hone ka sanket deti hain.", scientific: "Many lines suggest high cognitive-emotional processing and sensitivity to context.", luxury: "Your palm reads like a high-resolution sensor: perception is strong, but mental noise must be managed.", confidenceBase: 67, severity: "growth" }),
  makeRule({ id: "line_density_few_focus", title: "Few lines direct focus", category: "hand_shape", path: "palm.lineDensity", value: "few", classical: "Kam rekhaen sidhi pravritti, spashtata aur kam vikshipt man ko darshati hain.", scientific: "Fewer lines point to directness, lower distraction and simpler decision loops.", luxury: "Your hand shows clean signal over noise: fewer but stronger priorities shape your path.", confidenceBase: 64 }),
];
