import { makeRule } from "./_factory";

const clearLines: Array<[string, string, string, string, string]> = [
  ["life", "Life line vitality", "Ayu rekha spasht ho to jeevan shakti aur recovery capacity acchi mani jati hai.", "A clear life line supports vitality and recovery capacity, not lifespan prediction.", "no_death"],
  ["head", "Head line clarity", "Mastishk rekha spasht ho to vichar, vivek aur nirnay shakti balwan hoti hai.", "A clear head line supports organized thinking and decision quality.", ""],
  ["heart", "Heart line clarity", "Hridaya rekha spasht ho to bhavnaon mein sachchai aur sambandhon mein nishtha hoti hai.", "A clear heart line supports emotional honesty and stable attachment patterns.", ""],
  ["saturn", "Fate line visibility", "Bhagya/Saturn rekha dikhe to karmakshetra aur disha ka prabhav badhta hai.", "A visible fate line supports career direction and a sense of responsibility.", ""],
  ["sun", "Sun line visibility", "Surya rekha dikhe to pratibha, kala aur prashansa ke avsar milte hain.", "A visible Sun line supports creative recognition and reputation-building.", ""],
  ["mercury", "Mercury line visibility", "Budh rekha vani, vyapar aur sampark ka sanket deti hai.", "A visible Mercury line supports communication and business instincts.", ""],
];

export const MAJOR_LINE_RULES = [
  ...clearLines.map(([line, title, classical, scientific, guardrail]) =>
    makeRule({ id: `line_${line}_clear`, title, category: line === "life" ? "vitality" : "major_lines", path: `lines.${line}.clarity`, value: "clear", sourceIds: ["WRITER_LINES_III", "FIFTY_HANDPRINTS"], classical, scientific, luxury: `${title} is one of your cleaner signals. Read it as a probability pattern, then verify it with mounts, thumb and hand shape.`, confidenceBase: 70, guardrail: guardrail === "no_death" ? "no_death" : undefined })
  ),
  makeRule({ id: "life_deep_vitality", title: "Deep life line vitality", category: "vitality", path: "lines.life.depth", value: "deep", sourceIds: ["WRITER_LINES_III"], classical: "Gahri ayu rekha majboot prana shakti ka sanket hai, aayu ki nischit ganana nahi.", scientific: "A deep life line is read as vitality and resilience, not as a death-age marker.", luxury: "Your vitality signature is strong. Treat it as energy capacity that still needs sleep, food and rhythm.", confidenceBase: 71, guardrail: "no_death" }),
  makeRule({ id: "life_fork_moon_travel", title: "Life line fork toward Moon", category: "travel", path: "lines.life.forkDirection", value: "moon", sourceIds: ["WRITER_LINES_III"], classical: "Ayu rekha ka chandra disha mein fork yatra, videsh sambandh ya sthaan parivartan ka yog dikhata hai.", scientific: "A fork toward Moon is interpreted as movement, travel or relocation tendency, never guaranteed settlement.", luxury: "Your life path shows a movement signature: travel, relocation or cross-cultural environments can shape growth.", confidenceBase: 69, guardrail: "no_guarantee" }),
  makeRule({ id: "head_to_moon_imagination", title: "Head line toward Moon", category: "major_lines", path: "lines.head.direction", value: "moon", sourceIds: ["WRITER_LINES_III", "WRITER_SCIENTIFIC_IV"], classical: "Mastishk rekha chandra ki aur jaye to kalpana, bhavna aur rachnatmak buddhi badhti hai.", scientific: "A moon-directed head line supports imagination, empathy and nonlinear thinking.", luxury: "Your mind travels beyond the obvious: story, design, intuition and emotional intelligence are active assets.", confidenceBase: 72 }),
  makeRule({ id: "heart_jupiter_idealism", title: "Heart line ending Jupiter", category: "relationship", path: "lines.heart.ending", value: "jupiter", sourceIds: ["WRITER_LINES_III"], classical: "Hridaya rekha Guru par samapt ho to prem mein adarsh, maryada aur uchch apeksha hoti hai.", scientific: "A heart line ending near Jupiter suggests idealism, loyalty and high standards in love.", luxury: "Your love pattern is selective and principled; respect and emotional dignity matter more than casual attention.", confidenceBase: 71, guardrail: "no_guarantee" }),
  makeRule({ id: "line_break_caution", title: "Break signs reduce certainty", category: "major_lines", path: "signs.break", value: true, sourceIds: ["FIFTY_HANDPRINTS"], classical: "Rekha bhang ko akela bhay ka karan na manein; anya chihnon se milakar hi arth nikaalein.", scientific: "Breaks reduce confidence and require multi-sign confirmation before interpretation.", luxury: "Interrupted markings ask for careful interpretation. AstroLife lowers certainty and looks for supporting signs.", confidenceBase: 58, severity: "watch" }),
  makeRule({ id: "triangle_skill", title: "Triangle sign skill pattern", category: "major_lines", path: "signs.triangle", value: true, sourceIds: ["DAYANAND_SECRETS"], classical: "Trikon chihna yogya prayas, buddhi aur sanrachit labh ka sanket ho sakta hai.", scientific: "Triangle signs are read as structured skill, problem solving or technical advantage when supported.", luxury: "A triangle marking adds a precision signal: strategy, learning and skill conversion can become gains.", confidenceBase: 66 }),
  makeRule({ id: "travel_visible_movement", title: "Visible travel line movement", category: "travel", path: "lines.travel.visible", value: true, sourceIds: ["WRITER_LINES_III"], classical: "Yatra rekha dikhne par gati, deshantar ya parivartan ki pravritti dekhi jati hai.", scientific: "Visible travel indicators suggest movement and environmental change, not guaranteed migration.", luxury: "Your palm carries a movement code: travel, remote networks or relocation themes can become meaningful.", confidenceBase: 65, guardrail: "no_guarantee" }),
  makeRule({ id: "intuition_visible_inner_sense", title: "Visible intuition line", category: "major_lines", path: "lines.intuition.visible", value: true, sourceIds: ["WRITER_LINES_III"], classical: "Antar drishti rekha suksma anubhav aur bhavishya-bodh ki samvedana ka sanket hai.", scientific: "An intuition line is interpreted as pattern sensitivity and subconscious signal detection.", luxury: "Your inner radar is active; use it with evidence so intuition becomes intelligence.", confidenceBase: 64 }),
  makeRule({ id: "island_low_confidence", title: "Island sign lowers certainty", category: "major_lines", path: "signs.island", value: true, sourceIds: ["FIFTY_HANDPRINTS"], classical: "Dweep chihna ko akela vipatti na manein; yah dhyan aur urja ke leak ka sanket ho sakta hai.", scientific: "Island signs reduce clarity and should be read as stress or diffusion markers only with support.", luxury: "An island mark asks for refinement: protect attention, energy and decision quality.", confidenceBase: 56, severity: "watch" }),
  makeRule({ id: "square_protection_marker", title: "Square protective marker", category: "major_lines", path: "signs.square", value: true, sourceIds: ["DAYANAND_SECRETS"], classical: "Chaturasra chihna kai paramparaon mein raksha, sanrachna aur sambhal ka sanket mana gaya hai.", scientific: "Square signs can indicate containment, protection or stabilizing structure around a challenge.", luxury: "A square mark suggests the system can contain pressure when structure is present.", confidenceBase: 63 }),
  makeRule({ id: "star_visibility_spike", title: "Star sign visibility spike", category: "major_lines", path: "signs.star", value: true, sourceIds: ["DAYANAND_SECRETS"], classical: "Tara chihna ko sthaan ke anusaar prabhav, chamatkar ya achanak pehchan se joda gaya hai.", scientific: "Star signs are treated as high-intensity markers requiring category context.", luxury: "A star mark is a high-voltage signal: powerful, visible and best handled with maturity.", confidenceBase: 60, severity: "strong" }),
  makeRule({ id: "grille_diffused_energy", title: "Grille diffused energy", category: "major_lines", path: "signs.grille", value: true, sourceIds: ["WRITER_LINES_III"], classical: "Jaal chihna urja ke vitran aur kabhi-kabhi vikshipt pravritti ka sanket deta hai.", scientific: "Grille markings suggest scattered energy in the relevant area.", luxury: "Grille patterns say: simplify the field, reduce noise and protect your focus.", confidenceBase: 57, severity: "growth" }),
  makeRule({ id: "fork_adaptive_paths", title: "Fork sign adaptive paths", category: "major_lines", path: "signs.fork", value: true, sourceIds: ["WRITER_LINES_III"], classical: "Fork do dishaon, vikalpon aur anukoolan shakti ka sanket ho sakta hai.", scientific: "Forks indicate branching choices, adaptation and dual pathways.", luxury: "A fork mark shows your path can split intelligently; choose the branch that compounds skill.", confidenceBase: 63 }),
  makeRule({ id: "clear_head_visible_fate_execution", title: "Clear head with fate execution", category: "career", path: "lines.head.clarity", value: "clear", supporting: [{ path: "lines.saturn.visible", equals: true }, { path: "thumb.length", equals: "long" }], sourceIds: ["FIFTY_HANDPRINTS", "WRITER_SCIENTIFIC_IV"], classical: "Spasht mastishk rekha, bhagya rekha aur lamba angutha milkar yojana se siddhi ka yog banate hain.", scientific: "Clear thinking plus visible career direction plus willpower supports execution reliability.", luxury: "This is an operator pattern: strategy, direction and willpower can convert ideas into outcomes.", confidenceBase: 76 }),
];
