import { makeRule } from "./_factory";

export const RELATIONSHIP_RULES = [
  makeRule({ id: "heart_clear_venus_strong", title: "Warm loyal relationship style", category: "relationship", path: "lines.heart.clarity", value: "clear", supporting: [{ path: "mounts.venus.prominence", equals: "strong" }], sourceIds: ["WRITER_LINES_III", "SAMUDRIK_SHASTRA"], classical: "Spasht hridaya rekha aur balwan Shukra prem mein nishtha, garmahat aur dayaluta dikhate hain.", scientific: "Clear heart line plus strong Venus supports warmth, loyalty and emotionally embodied affection.", luxury: "Your relationship blueprint favors loyal warmth: consistency and respect unlock emotional depth.", confidenceBase: 74, guardrail: "no_guarantee" }),
  makeRule({ id: "heart_chained_emotional_noise", title: "Chained heart line emotional noise", category: "relationship", path: "lines.heart.clarity", value: "chained", classical: "Janjirdar hridaya rekha bhavnaon mein uljhan ya atyadhik samvedansheelta dikha sakti hai.", scientific: "A chained heart line can indicate emotional sensitivity and trust calibration needs.", luxury: "Your heart system may process subtle signals intensely; emotional boundaries become premium self-care.", confidenceBase: 62, severity: "growth", guardrail: "no_guarantee" }),
  makeRule({ id: "jupiter_heart_standards", title: "High relationship standards", category: "relationship", path: "lines.heart.ending", value: "jupiter", supporting: [{ path: "mounts.jupiter.prominence", equals: "strong" }], classical: "Guru prabhav prem mein maryada, uchch soch aur pratishtha ki ichha deta hai.", scientific: "Jupiter-linked heart indicators suggest high standards and principled attachment.", luxury: "You do not bond casually; your best partnership honors growth, dignity and shared ambition.", confidenceBase: 73, guardrail: "no_guarantee" }),
  makeRule({ id: "venus_weak_affection_training", title: "Affection expression needs training", category: "relationship", path: "mounts.venus.prominence", value: "weak", classical: "Shukra kamjor ho to prem ki abhivyakti ko jagrit karna upyogi hai.", scientific: "Quieter Venus can reflect guarded affection or lower expressive warmth.", luxury: "Affection may be present but less visible; intentional warmth improves relational outcomes.", confidenceBase: 58, severity: "growth", guardrail: "no_guarantee" }),
  makeRule({ id: "cross_sign_relationship_caution", title: "Cross sign caution", category: "relationship", path: "signs.cross", value: true, classical: "Cross chihna ko akela dosh na manein; sambandh arth ke liye anya rekhaon se milan zaruri hai.", scientific: "Cross markings require context and should not be used to predict divorce or separation.", luxury: "A cross marking simply asks for mature communication and slower conclusions in relationship analysis.", confidenceBase: 56, severity: "watch", guardrail: "no_guarantee" }),
  makeRule({ id: "branch_growth_relationship", title: "Branch sign relational growth", category: "relationship", path: "signs.branch", value: true, classical: "Upar ki shaakha vikas, sahayata aur naye avsar ka sanket ho sakti hai.", scientific: "Branching signs can show development pathways and growth through supportive relationships.", luxury: "Branching marks indicate your emotional life improves through growth-minded choices, not passive waiting.", confidenceBase: 64, guardrail: "no_guarantee" }),
  makeRule({ id: "many_lines_sensitive_bonding", title: "Sensitive bonding style", category: "relationship", path: "palm.lineDensity", value: "many", supporting: [{ path: "lines.heart.visible", equals: true }], classical: "Bahut rekhaen aur hridaya rekha milkar samvedansheel prem prakriti dikhate hain.", scientific: "High line density plus visible heart line suggests sensitive bonding and context awareness.", luxury: "You read emotional micro-signals quickly; the work is separating intuition from anxiety.", confidenceBase: 65, severity: "growth" }),
  makeRule({ id: "balanced_thumb_relationship_boundary", title: "Healthy boundaries in love", category: "relationship", path: "thumb.angle", value: "balanced", supporting: [{ path: "lines.heart.clarity", equals: "clear" }], classical: "Santulit angutha aur spasht hridaya rekha prem mein maryada aur vyavaharikta laate hain.", scientific: "Balanced thumb angle with clear heart line supports warmth with boundaries.", luxury: "Your strongest partnership pattern is caring without self-erasure.", confidenceBase: 70 }),
];
