import { makeRule } from "./_factory";

export const REMEDIES_RULES = [
  makeRule({ id: "remedy_many_lines_journaling", title: "Journaling for high line density", category: "remedies", path: "palm.lineDensity", value: "many", classical: "Adhik rekhaon wale vyakti ko niyamit likhit manan aur pranayam se man sthir karna chahiye.", scientific: "High processing signs benefit from journaling, breathwork and decision windows.", luxury: "Your premium remedy is signal hygiene: journal, breathe, decide once, then stop reprocessing.", confidenceBase: 68 }),
  makeRule({ id: "remedy_weak_jupiter_mentorship", title: "Mentorship for Jupiter", category: "remedies", path: "mounts.jupiter.prominence", value: "weak", classical: "Guru tattva ke liye guru seva, adhyayan aur sadachar upyogi hai.", scientific: "Quieter Jupiter improves through mentorship, ethical leadership practice and public responsibility.", luxury: "Build Jupiter through mentorship, teaching and visible integrity.", confidenceBase: 62 }),
  makeRule({ id: "remedy_weak_mercury_communication", title: "Communication practice for Mercury", category: "remedies", path: "mounts.mercury.prominence", value: "weak", classical: "Budh ke liye vani shuddhi, lekhan aur ganit/adhyayan ka abhyas laabhdayak hai.", scientific: "Mercury grows through writing, speaking practice and structured negotiation.", luxury: "Train Mercury with daily writing, clear offers and careful listening.", confidenceBase: 62 }),
  makeRule({ id: "remedy_weak_venus_warmth", title: "Warmth practice for Venus", category: "remedies", path: "mounts.venus.prominence", value: "weak", classical: "Shukra ke liye saundarya, safai, premal vyavahar aur sangeet upyogi hai.", scientific: "Venus balance improves through relational warmth, aesthetic care and body restoration.", luxury: "Restore Venus through music, beauty, hydration, affection and embodied rest.", confidenceBase: 62 }),
  makeRule({ id: "remedy_life_deep_routine", title: "Protect strong vitality with routine", category: "remedies", path: "lines.life.depth", value: "deep", classical: "Majboot prana shakti ko niyam, bhojan aur neend se sanrakshit rakhein.", scientific: "Strong vitality still requires sleep, hydration, movement and stress hygiene.", luxury: "Your energy is an asset; protect it like capital with rhythm and recovery.", confidenceBase: 66, guardrail: "no_diagnosis" }),
  makeRule({ id: "remedy_moon_strong_sound", title: "Sound practice for Moon", category: "remedies", path: "mounts.moon.prominence", value: "strong", classical: "Chandra bal ke liye shaant sangeet, dhyan aur jal tattva santulan laabhdayak hai.", scientific: "Strong Moon benefits from calming music, sleep regularity and reflective practice.", luxury: "AstroSound fit: Yaman or Bhoopali for calm focus when imagination becomes overactive.", confidenceBase: 65 }),
  makeRule({ id: "remedy_mars_balanced_movement", title: "Movement for Mars balance", category: "remedies", path: "mounts.mars.prominence", value: "balanced", classical: "Mangal santulan ke liye sharirik prayas aur niyantrit sahas upyogi hai.", scientific: "Mars balance improves through movement, boundaries and constructive challenge.", luxury: "Channel Mars into training, boundaries and decisive but clean action.", confidenceBase: 64 }),
  makeRule({ id: "remedy_break_slow_decision", title: "Slow decisions with breaks", category: "remedies", path: "signs.break", value: true, classical: "Bhang chihna dikhe to jaldbazi se bachkar sahayak sanketon ko dekhein.", scientific: "Break signs suggest lowering certainty and using staged decisions.", luxury: "When signals are interrupted, use staged commitments and written checkpoints.", confidenceBase: 60 }),
];
