import { makeRule } from "./_factory";

export const THUMB_RULES = [
  makeRule({ id: "thumb_long_will", title: "Long thumb willpower", category: "thumb", path: "thumb.length", value: "long", sourceIds: ["SAMUDRIK_SHASTRA", "WRITER_SCIENTIFIC_IV"], classical: "Lamba angutha iccha shakti, vivek aur swayam niyantran ka pramukh sanket hai.", scientific: "A long thumb supports agency, self-direction and stronger executive control.", luxury: "Your thumb gives the report a leadership spine: decision power and self-command are natural assets.", confidenceBase: 72 }),
  makeRule({ id: "thumb_short_reactivity", title: "Short thumb reactivity", category: "thumb", path: "thumb.length", value: "short", classical: "Chhota angutha turant pratikriya aur kabhi-kabhi dridh nirnay ki kami dikha sakta hai.", scientific: "A shorter thumb can indicate reactive choices and a need for decision frameworks.", luxury: "Your will system benefits from structure: decisions become stronger when you slow the first impulse.", confidenceBase: 63, severity: "growth" }),
  makeRule({ id: "thumb_balanced_angle", title: "Balanced thumb angle", category: "thumb", path: "thumb.angle", value: "balanced", classical: "Santulit angutha kona dayaluta aur maryada dono ka yog hai.", scientific: "Balanced thumb angle suggests openness with boundaries.", luxury: "You show healthy access to people without losing your center: warmth and discretion can coexist.", confidenceBase: 69 }),
  makeRule({ id: "thumb_wide_angle", title: "Wide thumb angle independence", category: "thumb", path: "thumb.angle", value: "wide", classical: "Vistrit angutha kona udarta, swatantrata aur khule vyavahar ka sanket hai.", scientific: "Wide thumb opening favors independence, generosity and self-expression.", luxury: "Your hand wants room: autonomy, generosity and self-led projects activate your best nature.", confidenceBase: 68 }),
  makeRule({ id: "thumb_closed_guarded", title: "Closed thumb angle guardedness", category: "thumb", path: "thumb.angle", value: "closed", classical: "Band angutha kona sanrakshan, sankoch aur kabhi-kabhi vishwas ki dheemi prakriya dikhata hai.", scientific: "A closed thumb angle may indicate guarded trust and conservative risk appetite.", luxury: "Your system protects energy carefully; opening up works best when safety is proven.", confidenceBase: 62, severity: "watch" }),
  makeRule({ id: "thumb_first_long_drive", title: "Long first phalange drive", category: "thumb", path: "thumb.firstPhalange", value: "long", classical: "Pratham phal lamba ho to sankalp aur kriya shakti badhti hai.", scientific: "A long first phalange indicates drive, initiative and action orientation.", luxury: "Your execution switch is strong: when the goal is clear, you can move decisively.", confidenceBase: 70 }),
  makeRule({ id: "thumb_second_long_logic", title: "Long second phalange logic", category: "thumb", path: "thumb.secondPhalange", value: "long", classical: "Dwitiya phal lamba ho to yukti, tarka aur samajhdari prabal hoti hai.", scientific: "A long second phalange supports reasoning, negotiation and planning.", luxury: "Your thumb carries a strategist's logic: persuasion, planning and analysis refine your power.", confidenceBase: 70 }),
  makeRule({ id: "thumb_two_phalanges_balanced", title: "Will and logic balance", category: "thumb", path: "thumb.firstPhalange", value: "long", supporting: [{ path: "thumb.secondPhalange", equals: "medium" }, { path: "thumb.angle", equals: "balanced" }], classical: "Iccha shakti aur vivek ka mel vyakti ko uchch karya yogya banata hai.", scientific: "Will plus reasoning gives better self-regulation than will alone.", luxury: "Your best decisions come when instinct is filtered through logic, not suppressed by it.", confidenceBase: 74 }),
];
